"use client";

import { useState, useEffect } from 'react';
import { useSearchParams, useRouter } from 'next/navigation';
import { Tabs, TabsContent, TabsList, TabsTrigger } from '@/components/ui/tabs';
import { Card, CardHeader, CardTitle, CardDescription, CardContent } from '@/components/ui/card';
import { Input } from '@/components/ui/input';
import { Label } from '@/components/ui/label';
import { Button } from '@/components/ui/button';
import { Textarea } from '@/components/ui/textarea';
import { useResume } from '@/context/ResumeContext';
import { useToast } from '@/hooks/use-toast';
import { Sparkles, Plus, Trash2, Wand2, Loader2 } from 'lucide-react';
import { generateAbout } from '@/ai/flows/generate-about-section-flow';
import { rewriteResponsibilities } from '@/ai/flows/rewrite-job-responsibilities-flow';

export default function ProfilePage() {
  const searchParams = useSearchParams();
  const router = useRouter();
  const { toast } = useToast();
  const activeTab = searchParams.get('tab') || 'basics';
  const { data, updateBasics, updateAbout, addJob, updateJob, removeJob, addEducation, removeEducation } = useResume();

  const [isGeneratingAbout, setIsGeneratingAbout] = useState(false);
  const [rewritingJobId, setRewritingJobId] = useState<string | null>(null);

  const handleTabChange = (value: string) => {
    const params = new URLSearchParams(searchParams.toString());
    params.set('tab', value);
    router.replace(`?${params.toString()}`);
  };

  const onGenerateAbout = async () => {
    setIsGeneratingAbout(true);
    try {
      const result = await generateAbout({
        targetRoles: data.about.targetRoles.length ? data.about.targetRoles : ["Software Engineer"],
        strengths: data.about.strengths.length ? data.about.strengths : ["Leadership", "Problem Solving"],
        industries: data.about.industries.length ? data.about.industries : ["Tech"],
        achievements: data.about.achievements.length ? data.about.achievements : ["Built a successful app"],
        tone: data.about.tone || "Professional",
      });
      updateAbout({ longAbout: result.longAbout, shortBio: result.shortBio });
      toast({ title: "Success!", description: "About section generated by AI." });
    } catch (err) {
      toast({ variant: "destructive", title: "Error", description: "Failed to generate about section." });
    } finally {
      setIsGeneratingAbout(false);
    }
  };

  const onRewriteBullets = async (jobId: string) => {
    const job = data.experience.find(j => j.id === jobId);
    if (!job) return;

    setRewritingJobId(jobId);
    try {
      const result = await rewriteResponsibilities({
        rawBullets: job.responsibilities,
        jobTitle: job.position,
        company: job.company,
        targetRole: data.about.targetRoles[0] || "Professional Role",
      });
      updateJob(jobId, { responsibilities: result.bullets as [string, string, string] });
      toast({ title: "Updated!", description: "Bullet points polished by AI." });
    } catch (err) {
      toast({ variant: "destructive", title: "Error", description: "Failed to rewrite responsibilities." });
    } finally {
      setRewritingJobId(null);
    }
  };

  return (
    <div className="space-y-8 animate-in fade-in slide-in-from-bottom-2 duration-500">
      <header>
        <h1 className="text-3xl font-headline font-bold">Profile Settings</h1>
        <p className="text-muted-foreground">Manage your background and professional details.</p>
      </header>

      <Tabs value={activeTab} onValueChange={handleTabChange} className="w-full">
        <TabsList className="grid grid-cols-4 w-full mb-8">
          <TabsTrigger value="basics">Basics</TabsTrigger>
          <TabsTrigger value="about">About</TabsTrigger>
          <TabsTrigger value="experience">Experience</TabsTrigger>
          <TabsTrigger value="education">Education</TabsTrigger>
        </TabsList>

        <TabsContent value="basics">
          <Card>
            <CardHeader>
              <CardTitle>Basic Information</CardTitle>
              <CardDescription>The core details recruiters use to find and contact you.</CardDescription>
            </CardHeader>
            <CardContent className="grid grid-cols-1 md:grid-cols-2 gap-6">
              <div className="space-y-2">
                <Label>Full Name</Label>
                <Input value={data.basics.name} onChange={e => updateBasics({ name: e.target.value })} placeholder="John Doe" />
              </div>
              <div className="space-y-2">
                <Label>Professional Label</Label>
                <Input value={data.basics.label} onChange={e => updateBasics({ label: e.target.value })} placeholder="Senior Developer" />
              </div>
              <div className="space-y-2">
                <Label>Email</Label>
                <Input value={data.basics.email} onChange={e => updateBasics({ email: e.target.value })} placeholder="john@example.com" />
              </div>
              <div className="space-y-2">
                <Label>Phone</Label>
                <Input value={data.basics.phone} onChange={e => updateBasics({ phone: e.target.value })} placeholder="+1 234 567 890" />
              </div>
              <div className="space-y-2">
                <Label>LinkedIn URL</Label>
                <Input value={data.basics.linkedin} onChange={e => updateBasics({ linkedin: e.target.value })} placeholder="linkedin.com/in/johndoe" />
              </div>
              <div className="space-y-2">
                <Label>Location</Label>
                <Input value={data.basics.location} onChange={e => updateBasics({ location: e.target.value })} placeholder="San Francisco, CA" />
              </div>
            </CardContent>
          </Card>
        </TabsContent>

        <TabsContent value="about">
          <div className="grid grid-cols-1 lg:grid-cols-3 gap-6">
            <Card className="lg:col-span-2">
              <CardHeader>
                <CardTitle>The "About" Section</CardTitle>
                <CardDescription>A professional summary that captures your essence.</CardDescription>
              </CardHeader>
              <CardContent className="space-y-4">
                <div className="space-y-2">
                  <Label>Long About (80-120 words)</Label>
                  <Textarea 
                    className="min-h-[150px]" 
                    value={data.about.longAbout} 
                    onChange={e => updateAbout({ longAbout: e.target.value })}
                  />
                </div>
                <div className="space-y-2">
                  <Label>Short Bio (1-2 sentences)</Label>
                  <Input value={data.about.shortBio} onChange={e => updateAbout({ shortBio: e.target.value })} />
                </div>
              </CardContent>
            </Card>

            <Card>
              <CardHeader>
                <CardTitle className="flex items-center gap-2">
                  <Sparkles className="w-4 h-4 text-primary" />
                  AI Assistant
                </CardTitle>
                <CardDescription>Feed the AI some context to generate your sections.</CardDescription>
              </CardHeader>
              <CardContent className="space-y-4">
                <div className="space-y-2">
                  <Label>Target Roles (comma separated)</Label>
                  <Input 
                    placeholder="UI Designer, Frontend Engineer" 
                    value={data.about.targetRoles.join(', ')} 
                    onChange={e => updateAbout({ targetRoles: e.target.value.split(',').map(s => s.trim()) })} 
                  />
                </div>
                <div className="space-y-2">
                  <Label>Strengths</Label>
                  <Input 
                    placeholder="Swift, React, Leadership" 
                    value={data.about.strengths.join(', ')} 
                    onChange={e => updateAbout({ strengths: e.target.value.split(',').map(s => s.trim()) })} 
                  />
                </div>
                <Button 
                  onClick={onGenerateAbout} 
                  className="w-full gap-2" 
                  disabled={isGeneratingAbout}
                >
                  {isGeneratingAbout ? <Loader2 className="w-4 h-4 animate-spin" /> : <Wand2 className="w-4 h-4" />}
                  Generate About
                </Button>
              </CardContent>
            </Card>
          </div>
        </TabsContent>

        <TabsContent value="experience">
          <div className="space-y-6">
            <div className="flex justify-between items-center">
              <h2 className="text-xl font-bold">Work Experience</h2>
              <Button onClick={() => addJob({ 
                id: Math.random().toString(36).substr(2, 9),
                company: 'New Company',
                position: 'Role Name',
                startDate: '',
                endDate: '',
                responsibilities: ['', '', '']
              })} className="gap-2">
                <Plus className="w-4 h-4" /> Add Job
              </Button>
            </div>

            {data.experience.map((job) => (
              <Card key={job.id} className="relative group">
                <Button 
                  variant="ghost" 
                  size="icon" 
                  className="absolute top-2 right-2 opacity-0 group-hover:opacity-100 transition-opacity text-destructive"
                  onClick={() => removeJob(job.id)}
                >
                  <Trash2 className="w-4 h-4" />
                </Button>
                <CardContent className="p-6 space-y-4">
                  <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
                    <div className="space-y-2">
                      <Label>Company</Label>
                      <Input value={job.company} onChange={e => updateJob(job.id, { company: e.target.value })} />
                    </div>
                    <div className="space-y-2">
                      <Label>Position</Label>
                      <Input value={job.position} onChange={e => updateJob(job.id, { position: e.target.value })} />
                    </div>
                  </div>
                  <div className="space-y-2">
                    <div className="flex items-center justify-between">
                      <Label>Responsibilities (Exactly 3)</Label>
                      <Button 
                        variant="outline" 
                        size="sm" 
                        className="h-8 gap-2 border-primary/50"
                        onClick={() => onRewriteBullets(job.id)}
                        disabled={rewritingJobId === job.id}
                      >
                        {rewritingJobId === job.id ? <Loader2 className="w-3 h-3 animate-spin" /> : <Wand2 className="w-3 h-3" />}
                        Rewrite bullets
                      </Button>
                    </div>
                    {job.responsibilities.map((resp, idx) => (
                      <Input 
                        key={idx} 
                        value={resp} 
                        placeholder={`Bullet point ${idx + 1}`}
                        onChange={e => {
                          const newResps = [...job.responsibilities] as [string, string, string];
                          newResps[idx] = e.target.value;
                          updateJob(job.id, { responsibilities: newResps });
                        }}
                      />
                    ))}
                  </div>
                </CardContent>
              </Card>
            ))}
          </div>
        </TabsContent>

        <TabsContent value="education">
          <div className="space-y-6">
            <div className="flex justify-between items-center">
              <h2 className="text-xl font-bold">Education</h2>
              <Button onClick={() => addEducation({ 
                id: Math.random().toString(36).substr(2, 9),
                institution: 'University',
                area: 'Field of Study',
                studyType: 'Degree',
                startDate: '',
                endDate: ''
              })} className="gap-2">
                <Plus className="w-4 h-4" /> Add Education
              </Button>
            </div>

            {data.education.map((edu) => (
              <Card key={edu.id} className="relative group">
                <Button 
                  variant="ghost" 
                  size="icon" 
                  className="absolute top-2 right-2 opacity-0 group-hover:opacity-100 transition-opacity text-destructive"
                  onClick={() => removeEducation(edu.id)}
                >
                  <Trash2 className="w-4 h-4" />
                </Button>
                <CardContent className="p-6 grid grid-cols-1 md:grid-cols-2 gap-4">
                  <div className="space-y-2">
                    <Label>Institution</Label>
                    <Input value={edu.institution} />
                  </div>
                  <div className="space-y-2">
                    <Label>Degree Type</Label>
                    <Input value={edu.studyType} placeholder="Bachelor of Science" />
                  </div>
                  <div className="space-y-2">
                    <Label>Field of Study</Label>
                    <Input value={edu.area} placeholder="Computer Science" />
                  </div>
                </CardContent>
              </Card>
            ))}
          </div>
        </TabsContent>
      </Tabs>
    </div>
  );
}
