"use client";

import { useState } from 'react';
import { useSearchParams, useRouter } from 'next/navigation';
import { Tabs, TabsContent, TabsList, TabsTrigger } from '@/components/ui/tabs';
import { Card, CardHeader, CardTitle, CardDescription, CardContent } from '@/components/ui/card';
import { Input } from '@/components/ui/input';
import { Label } from '@/components/ui/label';
import { Button } from '@/components/ui/button';
import { Textarea } from '@/components/ui/textarea';
import { useResume } from '@/context/ResumeContext';
import { useToast } from '@/hooks/use-toast';
import { Sparkles, Plus, Trash2, Wand2, Loader2, Save, Gamepad2, Linkedin } from 'lucide-react';
import { generateAbout } from '@/ai/flows/generate-about-section-flow';
import { rewriteResponsibilities } from '@/ai/flows/rewrite-job-responsibilities-flow';

export default function ProfilePage() {
  const searchParams = useSearchParams();
  const router = useRouter();
  const { toast } = useToast();
  const activeTab = searchParams.get('tab') || 'basics';
  const { 
    data, 
    updateBasics, 
    updateAbout, 
    addJob, 
    updateJob, 
    removeJob, 
    addEducation, 
    updateEducation, 
    removeEducation,
  } = useResume();

  const [isGeneratingAbout, setIsGeneratingAbout] = useState(false);
  const [rewritingJobId, setRewritingJobId] = useState<string | null>(null);

  const handleTabChange = (value: string) => {
    const params = new URLSearchParams(searchParams.toString());
    params.set('tab', value);
    router.replace(`?${params.toString()}`);
  };

  const onGenerateAbout = async () => {
    setIsGeneratingAbout(true);
    try {
      const result = await generateAbout({
        targetRoles: data.about.targetRoles.length ? data.about.targetRoles : ["Software Engineer"],
        strengths: data.about.strengths.length ? data.about.strengths : ["Leadership", "Problem Solving"],
        industries: data.about.industries.length ? data.about.industries : ["Tech"],
        achievements: data.about.achievements.length ? data.about.achievements : ["Built a successful app"],
        tone: data.about.tone || "Professional",
      });
      updateAbout({ longAbout: result.longAbout, shortBio: result.shortBio });
      toast({ title: "Success!", description: "About section generated by AI." });
    } catch (err) {
      toast({ variant: "destructive", title: "Error", description: "Failed to generate about section." });
    } finally {
      setIsGeneratingAbout(false);
    }
  };

  const onRewriteResponsibilities = async (jobId: string) => {
    const job = data.experience.find(j => j.id === jobId);
    if (!job) return;

    setRewritingJobId(jobId);
    try {
      const result = await rewriteResponsibilities({
        rawBullets: job.responsibilities,
        jobTitle: job.position,
        company: job.company,
        targetRole: data.about.targetRoles[0] || "Professional Role",
      });
      updateJob(jobId, { responsibilities: result.bullets as [string, string, string] });
      toast({ title: "Updated!", description: "Bullet points polished by AI." });
    } catch (err) {
      toast({ variant: "destructive", title: "Error", description: "Failed to rewrite responsibilities." });
    } finally {
      setRewritingJobId(null);
    }
  };

  const handleSaveAll = () => {
    localStorage.setItem('resume-keeper-data', JSON.stringify(data));
    toast({ title: "Profile Saved", description: "Your professional data has been updated and secured." });
  };

  return (
    <div className="space-y-8 animate-in fade-in slide-in-from-bottom-2 duration-500">
      <header className="flex flex-col md:flex-row justify-between items-start md:items-center gap-4">
        <div>
          <h1 className="text-4xl font-headline font-bold text-foreground drop-shadow-sm">Profile Settings</h1>
          <p className="text-muted-foreground text-lg">Manage your background and professional details.</p>
        </div>
        <div className="flex gap-2 w-full md:w-auto">
          <Button onClick={handleSaveAll} variant="default" className="gap-2 flex-1 md:flex-none shadow-xl hover:scale-105 transition-transform px-6">
            <Save className="w-4 h-4" /> Save Profile
          </Button>
        </div>
      </header>

      <Tabs value={activeTab} onValueChange={handleTabChange} className="w-full">
        <TabsList className="grid grid-cols-4 w-full mb-8 bg-white/10 backdrop-blur-2xl p-1.5 rounded-2xl border border-white/30 shadow-lg">
          <TabsTrigger value="basics" className="rounded-xl data-[state=active]:bg-white/40 data-[state=active]:shadow-md">Basics</TabsTrigger>
          <TabsTrigger value="about" className="rounded-xl data-[state=active]:bg-white/40 data-[state=active]:shadow-md">About</TabsTrigger>
          <TabsTrigger value="experience" className="rounded-xl data-[state=active]:bg-white/40 data-[state=active]:shadow-md">Experience</TabsTrigger>
          <TabsTrigger value="education" className="rounded-xl data-[state=active]:bg-white/40 data-[state=active]:shadow-md">Education</TabsTrigger>
        </TabsList>

        <TabsContent value="basics">
          <Card className="bg-white/10 backdrop-blur-3xl border-white/40 shadow-2xl rounded-[2rem]">
            <CardHeader>
              <CardTitle className="text-2xl">Basic Information</CardTitle>
              <CardDescription className="text-base text-foreground/70">Core details recruiters use to find and contact you.</CardDescription>
            </CardHeader>
            <CardContent className="space-y-8">
              <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
                <div className="space-y-2">
                  <Label className="text-foreground/80">Full Name</Label>
                  <Input className="bg-white/30 border-white/30 text-lg h-12 rounded-xl" value={data.basics.name || ''} onChange={e => updateBasics({ name: e.target.value })} placeholder="John Doe" />
                </div>
                <div className="space-y-2">
                  <Label className="text-foreground/80">Professional Label</Label>
                  <Input className="bg-white/30 border-white/30 text-lg h-12 rounded-xl" value={data.basics.label || ''} onChange={e => updateBasics({ label: e.target.value })} placeholder="Senior Developer" />
                </div>
                <div className="space-y-2">
                  <Label className="text-foreground/80">Email</Label>
                  <Input className="bg-white/30 border-white/30 text-lg h-12 rounded-xl" value={data.basics.email || ''} onChange={e => updateBasics({ email: e.target.value })} placeholder="john@example.com" />
                </div>
                <div className="space-y-2">
                  <Label className="text-foreground/80">Phone</Label>
                  <Input className="bg-white/30 border-white/30 text-lg h-12 rounded-xl" value={data.basics.phone || ''} onChange={e => updateBasics({ phone: e.target.value })} placeholder="+1 234 567 890" />
                </div>
                <div className="space-y-2">
                  <Label className="text-foreground/80">Location</Label>
                  <Input className="bg-white/30 border-white/30 text-lg h-12 rounded-xl" value={data.basics.location || ''} onChange={e => updateBasics({ location: e.target.value })} placeholder="San Francisco, CA" />
                </div>
              </div>

              <div className="pt-8 border-t border-white/20">
                <h3 className="text-xl font-bold mb-6 text-primary drop-shadow-sm flex items-center gap-2">Social Profiles</h3>
                <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
                  <div className="space-y-2">
                    <Label className="flex items-center gap-2 text-foreground/80"><Linkedin className="w-5 h-5 text-primary" /> LinkedIn URL</Label>
                    <Input className="bg-white/30 border-white/30 text-lg h-12 rounded-xl" value={data.basics.linkedin || ''} onChange={e => updateBasics({ linkedin: e.target.value })} placeholder="linkedin.com/in/johndoe" />
                  </div>
                  <div className="space-y-2">
                    <Label className="flex items-center gap-2 text-foreground/80"><Gamepad2 className="w-5 h-5 text-primary" /> Discord Tag/Link</Label>
                    <Input className="bg-white/30 border-white/30 text-lg h-12 rounded-xl" value={data.basics.discord || ''} onChange={e => updateBasics({ discord: e.target.value })} placeholder="username#0000" />
                  </div>
                </div>
              </div>
            </CardContent>
          </Card>
        </TabsContent>

        <TabsContent value="about">
          <div className="grid grid-cols-1 lg:grid-cols-3 gap-8">
            <Card className="lg:col-span-2 bg-white/10 backdrop-blur-3xl border-white/40 shadow-2xl rounded-[2rem]">
              <CardHeader>
                <CardTitle className="text-2xl">The "About" Section</CardTitle>
                <CardDescription className="text-base text-foreground/70">A professional summary that captures your essence.</CardDescription>
              </CardHeader>
              <CardContent className="space-y-8">
                <div className="space-y-2">
                  <Label className="text-foreground/80 text-lg">Short Bio (Elevator Pitch)</Label>
                  <Textarea 
                    className="min-h-[140px] text-xl bg-white/30 border-white/30 rounded-2xl p-4 focus:bg-white/50 transition-colors" 
                    placeholder="Brief 1-2 sentence introduction..."
                    value={data.about.shortBio || ''} 
                    onChange={e => updateAbout({ shortBio: e.target.value })} 
                  />
                </div>
                <div className="space-y-2">
                  <Label className="text-foreground/80 text-lg">Long About (80-120 words)</Label>
                  <Textarea 
                    className="min-h-[260px] bg-white/30 border-white/30 text-lg rounded-2xl p-4 focus:bg-white/50 transition-colors" 
                    value={data.about.longAbout || ''} 
                    onChange={e => updateAbout({ longAbout: e.target.value })}
                  />
                </div>
              </CardContent>
            </Card>

            <Card className="bg-white/20 backdrop-blur-3xl border-white/40 shadow-2xl rounded-[2rem] h-fit sticky top-8">
              <CardHeader>
                <CardTitle className="flex items-center gap-2 text-2xl">
                  <Sparkles className="w-6 h-6 text-primary animate-pulse" />
                  AI Assistant
                </CardTitle>
                <CardDescription className="text-base text-foreground/70">Feed context to AI to generate these sections.</CardDescription>
              </CardHeader>
              <CardContent className="space-y-6">
                <div className="space-y-2">
                  <Label className="text-foreground/80">Target Roles</Label>
                  <Input 
                    className="bg-white/30 border-white/30 rounded-xl"
                    placeholder="UI Designer, Frontend Engineer" 
                    value={data.about.targetRoles.join(', ') || ''} 
                    onChange={e => updateAbout({ targetRoles: e.target.value.split(',').map(s => s.trim()) })} 
                  />
                </div>
                <div className="space-y-2">
                  <Label className="text-foreground/80">Strengths</Label>
                  <Input 
                    className="bg-white/30 border-white/30 rounded-xl"
                    placeholder="Swift, React, Leadership" 
                    value={data.about.strengths.join(', ') || ''} 
                    onChange={e => updateAbout({ strengths: e.target.value.split(',').map(s => s.trim()) })} 
                  />
                </div>
                <Button 
                  onClick={onGenerateAbout} 
                  className="w-full h-12 gap-2 shadow-lg hover:scale-[1.02] transition-transform text-lg" 
                  disabled={isGeneratingAbout}
                >
                  {isGeneratingAbout ? <Loader2 className="w-5 h-5 animate-spin" /> : <Wand2 className="w-5 h-5" />}
                  Generate Content
                </Button>
              </CardContent>
            </Card>
          </div>
        </TabsContent>

        <TabsContent value="experience">
          <div className="space-y-8">
            <div className="flex justify-between items-center">
              <h2 className="text-3xl font-bold text-foreground drop-shadow-sm">Work Experience</h2>
              <Button onClick={() => addJob({ 
                id: Math.random().toString(36).substr(2, 9),
                company: 'New Company',
                position: 'Role Name',
                startDate: '',
                endDate: '',
                responsibilities: ['', '', '']
              })} className="gap-2 shadow-xl hover:scale-105 transition-transform">
                <Plus className="w-4 h-4" /> Add Job
              </Button>
            </div>

            {data.experience.map((job) => (
              <Card key={job.id} className="relative group bg-white/10 backdrop-blur-3xl border-white/40 shadow-2xl rounded-[2rem] overflow-hidden">
                <Button 
                  variant="ghost" 
                  size="icon" 
                  className="absolute top-4 right-4 opacity-0 group-hover:opacity-100 transition-opacity text-destructive hover:bg-destructive/10"
                  onClick={() => removeJob(job.id)}
                >
                  <Trash2 className="w-5 h-5" />
                </Button>
                <CardContent className="p-8 space-y-6">
                  <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
                    <div className="space-y-2">
                      <Label className="text-foreground/80">Company</Label>
                      <Input className="bg-white/30 border-white/30 text-lg h-12 rounded-xl" value={job.company || ''} onChange={e => updateJob(job.id, { company: e.target.value })} />
                    </div>
                    <div className="space-y-2">
                      <Label className="text-foreground/80">Position</Label>
                      <Input className="bg-white/30 border-white/30 text-lg h-12 rounded-xl" value={job.position || ''} onChange={e => updateJob(job.id, { position: e.target.value })} />
                    </div>
                  </div>
                  <div className="space-y-4">
                    <div className="flex items-center justify-between">
                      <Label className="text-lg font-bold text-primary">Responsibilities (Exactly 3)</Label>
                      <Button 
                        variant="outline" 
                        size="sm" 
                        className="h-10 gap-2 border-primary/50 bg-white/20 hover:bg-white/40 shadow-sm rounded-xl"
                        onClick={() => onRewriteResponsibilities(job.id)}
                        disabled={rewritingJobId === job.id}
                      >
                        {rewritingJobId === job.id ? <Loader2 className="w-4 h-4 animate-spin" /> : <Wand2 className="w-4 h-4" />}
                        Rewrite with AI
                      </Button>
                    </div>
                    <div className="grid gap-3">
                      {job.responsibilities.map((resp, idx) => (
                        <Input 
                          key={idx} 
                          className="bg-white/30 border-white/30 text-base h-11 rounded-xl focus:bg-white/50 transition-colors"
                          value={resp || ''} 
                          placeholder={`Accomplishment ${idx + 1}...`}
                          onChange={e => {
                            const newResps = [...job.responsibilities] as [string, string, string];
                            newResps[idx] = e.target.value;
                            updateJob(job.id, { responsibilities: newResps });
                          }}
                        />
                      ))}
                    </div>
                  </div>
                </CardContent>
              </Card>
            ))}
          </div>
        </TabsContent>

        <TabsContent value="education">
          <div className="space-y-8">
            <div className="flex justify-between items-center">
              <h2 className="text-3xl font-bold text-foreground drop-shadow-sm">Education</h2>
              <Button onClick={() => addEducation({ 
                id: Math.random().toString(36).substr(2, 9),
                institution: 'University',
                area: 'Field of Study',
                studyType: 'Degree',
                startDate: '',
                endDate: ''
              })} className="gap-2 shadow-xl hover:scale-105 transition-transform">
                <Plus className="w-4 h-4" /> Add Education
              </Button>
            </div>

            {data.education.map((edu) => (
              <Card key={edu.id} className="relative group bg-white/10 backdrop-blur-3xl border-white/40 shadow-2xl rounded-[2rem] overflow-hidden">
                <Button 
                  variant="ghost" 
                  size="icon" 
                  className="absolute top-4 right-4 opacity-0 group-hover:opacity-100 transition-opacity text-destructive hover:bg-destructive/10"
                  onClick={() => removeEducation(edu.id)}
                >
                  <Trash2 className="w-5 h-5" />
                </Button>
                <CardContent className="p-8 grid grid-cols-1 md:grid-cols-2 gap-8">
                  <div className="space-y-2">
                    <Label className="text-foreground/80">Institution</Label>
                    <Input 
                      className="bg-white/30 border-white/30 text-lg h-12 rounded-xl"
                      value={edu.institution || ''} 
                      onChange={e => updateEducation(edu.id, { institution: e.target.value })} 
                    />
                  </div>
                  <div className="space-y-2">
                    <Label className="text-foreground/80">Degree Type</Label>
                    <Input 
                      className="bg-white/30 border-white/30 text-lg h-12 rounded-xl"
                      value={edu.studyType || ''} 
                      placeholder="Bachelor of Science" 
                      onChange={e => updateEducation(edu.id, { studyType: e.target.value })} 
                    />
                  </div>
                  <div className="space-y-2">
                    <Label className="text-foreground/80">Field of Study</Label>
                    <Input 
                      className="bg-white/30 border-white/30 text-lg h-12 rounded-xl"
                      value={edu.area || ''} 
                      placeholder="Computer Science" 
                      onChange={e => updateEducation(edu.id, { area: e.target.value })} 
                    />
                  </div>
                </CardContent>
              </Card>
            ))}
          </div>
        </TabsContent>
      </Tabs>
    </div>
  );
}
